config/routes.rb
Aufree::Application.routes.draw do
  resources :users  do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root to: 'static_pages#home'    
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
  def self.from_users_followed_by(user)
    followed_user_ids = user.followed_user_ids
    where("user_id IN (?) OR user_id = ?", followed_user_ids, user)
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
	validates :follower_id, presence: true
	validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                     class_name:  "Relationship",
                                     dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
	before_save { email.downcase! }
	before_create :create_remember_token
	validates :name,  presence: true, length: { maximum: 20 }, uniqueness: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true,
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, length: { minimum: 6 }

    def User.new_remember_token
    	SecureRandom.urlsafe_base64
    end

    def User.hash(token)
    	Digest::SHA1.hexdigest(token.to_s)
    end

    def feed
      Micropost.from_users_followed_by(self)
    end

    def following?(other_user)
      relationships.find_by(followed_id: other_user.id)
    end

    def follow!(other_user)
      relationships.create!(followed_id: other_user.id)
    end

    def unfollow!(other_user)
      relationships.find_by(followed_id: other_user.id).destroy
    end

    private

  		 def create_remember_token
  		 	self.remember_token = User.hash(User.new_remember_token)
  		 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def create
  	@micropost = current_user.microposts.build(micropost_params)
  	if @micropost.save
  		flash[:success] = "成功发布微博"
  		redirect_to root_url
  	else
  		@feed_items = []
  		render 'static_pages/home'
  	end
  end

  def destroy
    @micropost.destroy
    redirect_to root_url
  end

  private

  	def micropost_params
  		params.require(:micropost).permit(:content)
  	end

  	def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :signed_in_user

  respond_to :html, :js

  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    respond_with @user
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    respond_with @user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_back_or user
		else
			flash.now[:error] = '邮箱或密码输入有误'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def contact
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

   def index
    @users = User.paginate(page: params[:page])
   end

  def show
  	@user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def new
  	 @user = User.new
  end

  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      sign_in @user
      flash[:success] = "欢迎进入 Aufree"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "个人资料更新成功!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "用户已成功删除."
    redirect_to users_url
  end

  def following
    @title = "关注"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "粉丝"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

private 

  def user_params
  	params.require(:user).permit(:name, :email, :password,
  								 :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Aufree"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper

  def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  private

    def wrap_long_string(text, max_width = 30)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text :
                                  text.scan(regex).join(zero_width_space)
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.hash(remember_token))
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.hash(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
		user == current_user
	end

	def signed_in_user
		unless signed_in?
			store_location
			redirect_to signin_url, notice: "请先登录"
		end
	end

	def sign_out
		current_user.update_attribute(:remember_token,
									  User.hash(User.new_remember_token))
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def redirect_back_or(default)
	    redirect_to(session[:return_to] || default)
	    session.delete(:return_to)
	end
	
	def store_location
	  session[:return_to] = request.fullpath if request.get?
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, options = { size: 50 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://freetalks.herokuapp.com/">The web site</a>
    by Paul King
  </small>
  <nav>
    <ul>
      <li><%= link_to "关于",   about_path %></li>
      <li><%= link_to "联系", contact_path %></li>
      <li><a href="#">更新</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Aufree", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li>
            <%= link_to root_path do %>
              <i class="fa fa-home"></i>主页
            <% end %>
          </li>
          <li>
            <%= link_to help_path do %>
              <i class="fa fa-paper-plane"></i>帮助
            <% end %>
          </li>
          <% if signed_in? %>
            <li>
              <%= link_to users_path do %>
                <i class="fa fa-users"></i>用户
              <% end %>
            </li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-anchor"></i>
                账户 <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to current_user do %>
                   <i class="fa fa-book"></i>资料
                  <% end %>
                </li>
                <li><%= link_to edit_user_path(current_user) do %>
                  <i class="fa fa-cog"></i>设置
                  <% end %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to signout_path, method: "delete" do %>
                    <i class="fa fa-power-off"></i>退出
                  <% end %>
                </li>
              </ul>
            </li>
          <% else %>
            <li>
              <%= link_to signin_path do %>
                <i class="fa fa-sign-in"></i>登录
              <% end %>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
  <!-- [if lt IE9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]  -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
<%= render'layouts/shim' %>
</head>
<body>
<%= render'layouts/header'%>
    <div class="container">
    	<% flash.each do | key,value | %>
    	<div class="alert alert-<%= key %>">
    		<%= value %>
    	</div>
    	<% end %>
      <%= yield %>
    <%= render'layouts/footer'%>
    <%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/microposts/_micropost.html.erb
<li>
	<span class="content"><%= micropost.content %></span>
	<div class="feed-item-right">
		<span class="timestamp">
			在<%= time_ago_in_words(micropost.created_at) %>前发布
		</span>
		<% if current_user?(micropost.user) %>
		<%= link_to "X", micropost, method: :delete,
		data: { confirm: "您确定要删除该微博?" },
		title: "删除微博" %>
		<% end %>
	</div>
</li>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      表单包含 <%= object.errors.count %> 个错误.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <div class="feed-item-right">
    <span class="timestamp">
      在<%= time_ago_in_words(feed_item.created_at) %>前发布
    </span>
    <% if current_user?(feed_item.user) %>
    <%= link_to "X", feed_item, method: :delete,
    data: { confirm: "确认删除?" },
    title: "删除微博" %>
    <% end %>
  </div>
</li>

app/views/shared/_micropost_feed.html.erb
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="span8">
      <h3>微博列表</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "写点啥呗..." %>
  </div>
  <%= f.submit "发布", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="center">
  <div class="stats">
    <a href="<%= following_user_path(@user) %>">
      关注
      <strong id="following" class="stat">
        <%= @user.followed_users.count %>
      </strong>
    </a>
    <a href="<%= followers_user_path(@user) %>">
      粉丝
      <strong id="followers" class="stat">
        <%= @user.followers.count %>
      </strong>
    </a>
    <a href="<%= user_path(@user) %>">
      微博
      <strong id="microposts" class="stat">
        <%= @user.microposts.count %>
      </strong>
    </a>
  </div>
</div>

app/views/shared/_user_info.html.erb
<a class="user-gravatar" href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 460 %>
</a>
<h1>
  <%= current_user.name %>
</h1>

app/views/shared/_welcome.html.erb
 <div class="center hero-unit">
    <h1>欢迎来到</h1>
    <h1>Aufree</h1>

	 <%= link_to image_tag("luffy.png", alt: "Luffy"), signup_path %>

    <%= link_to "现在注册!", signup_path,
                                class: "btn btn-large btn-primary signup" %>
    
  </div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>关于我</h1>
<p class="center">李锦发,大一学生,Ruby on Rails Developer</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>联系</h1>
<p class="center"><span class="contact">freedomlijinfa@gmail.com</span></p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>帮助</h1>
<p></p>

app/views/static_pages/home.html.erb
<% if signed_in? %>

<%= render 'shared/micropost_feed' %>
<% else %>
 <%= render 'shared/welcome' %>
<% end %>

app/views/users/_fields.html.erb

    <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "用户名" %>
      <%= f.text_field :name %>

      <%= f.label :email, "邮箱" %>
      <%= f.text_field :email %>

      <%= f.label :password, "密码" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "确认密码" %>
      <%= f.password_field :password_confirmation %>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id),
             remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "关注", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "取消", class: "btn btn-large" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "X", user, method: :delete,
                                  data: { confirm: "确认删除?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>更新资料</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

      <%= render 'fields', f: f %>
 
      <%= f.submit "保存", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for (@user) %>
    <a href="http://gravatar.com/emails" target="_blank">更改头像</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>所有用户</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>注册</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>

      <%= f.submit "完成注册", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section>
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="span8">
    <%= render 'follow_form' if signed_in? %>
    <% if @user.microposts.any? %>
      <h3>微博 (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="span4">
    <section>
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
    </section>
    <section>
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>